version: "3.8"
services:
  redis: 
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  app:
    container_name: core-service
    image: ${IMAGE_NAME:-core-service}:${IMAGE_TAG:-latest}
    build:
      context: .
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    command: npm start
    environment:
      NODE_ENV: production
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
      ALCHEMY_API_MAINNET_URL: ${ALCHEMY_API_MAINNET_URL}
      ALCHEMY_API_RINKEBY_URL: ${ALCHEMY_API_RINKEBY_URL}
      ETH_RPC_MAINNET: ${ETH_RPC_MAINNET}
      ETH_RPC_RINKEBY: ${ETH_RPC_RINKEBY}
      GEMXYZ_API_KEY: ${GEMXYZ_API_KEY}
      LUNARCRUSH_API_KEY: ${LUNARCRUSH_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
      MONGO_URI: ${MONGO_URI}
      WORKER_URL: ${WORKER_URL}
      MORALIS_API_KEY: ${MORALIS_API_KEY}
      NFTBANK_API_KEY: ${NFTBANK_API_KEY}
      OPENSEA_API_KEY: ${OPENSEA_API_KEY}
      SUBGRAPH_API_MAINNET_URL: ${SUBGRAPH_API_MAINNET_URL}
      SUBGRAPH_API_RINKEBY_URL: ${SUBGRAPH_API_RINKEBY_URL}
