version: "3.8"
services:
  app:
    image: ${IMAGE_NAME:-core-service}:${IMAGE_TAG:-test}
    container_name: core-service
    command: npm test
    build:
      context: .
      target: test
    ports:
      - 8080:8080
    environment:
      NODE_ENV: test
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
      ALCHEMY_API_MAINNET_URL: ${ALCHEMY_API_MAINNET_URL}
      ALCHEMY_API_RINKEBY_URL: ${ALCHEMY_API_RINKEBY_URL}
      ETH_RPC_MAINNET: ${ETH_RPC_MAINNET}
      ETH_RPC_RINKEBY: ${ETH_RPC_RINKEBY}
      GEMXYZ_API_KEY: ${GEMXYZ_API_KEY}
      LUNARCRUSH_API_KEY: ${LUNARCRUSH_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
      MONGO_URI: ${MONGO_URI}
      WORKER_URL: ${WORKER_URL}
      MORALIS_API_KEY: ${MORALIS_API_KEY}
      NFTBANK_API_KEY: ${NFTBANK_API_KEY}
      OPENSEA_API_KEY: ${OPENSEA_API_KEY}
      SUBGRAPH_API_MAINNET_URL: ${SUBGRAPH_API_MAINNET_URL}
      SUBGRAPH_API_RINKEBY_URL: ${SUBGRAPH_API_RINKEBY_URL}
      TESTS_WALLET_ADDRESS: ${TESTS_WALLET_ADDRESS}
      TESTS_WHALE_WALLET_ADDRESSES: ${TESTS_WHALE_WALLET_ADDRESSES}
      TESTS_WALLET_PRIVATE_KEY: ${TESTS_WALLET_PRIVATE_KEY}
