nameSuffix: -prod
resources: ['../../base']
patches:
- path: job-patch.yaml
  target:
    kind: Job
- patch: |-
    - op: add
      path: "/spec/template/spec/template/spec/containers/0/env/-"
      value:
        name: REDISHOST
        value: "10.210.137.92"
  target:
    kind: Job
