apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: sa-core-service-staging@pinedefi.iam.gserviceaccount.com
          volumes:
          - name: env
            secret:
              secretName: core-service-env-vars-staging
              items:
              - key: latest
                path: .env
