apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: job
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/vpc-access-connector: projects/pinedefi/locations/us-central1/connectors/core
    spec:
      template:
        spec:
          serviceAccountName: sa-core-service-staging@pinedefi.iam.gserviceaccount.com
          volumes:
          - name: env
            secret:
              secretName: core-service-env-vars-staging
              items:
              - key: latest
                path: .env
