name: CD
on:
  push:
    branches: [development, staging, main]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      push: true
      environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    secrets: inherit
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
  notify:
    name: Notify
    needs: [deploy]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/slack-action@v1.0.0
        with:
          success-prefix: 🌲
          success: ${{ needs.deploy.result == 'success' }}
          webhook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
