name: CD
on:
  push:
    branches: [development, staging, main]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/job-build.yml
    with:
      image_name: gcr.io/pinedefi/core-service
      push: true
      use_prod_apis: ${{ github.ref_name == 'main' }}
    secrets: inherit
  deploy:
    name: Deploy
    uses: ./.github/workflows/job-deploy.yml
    needs: [build]
    with:
      cloud_run_ref_label: ${{ github.ref_name }}
      cloud_run_service_label: core
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
  notify:
    name: Notify
    needs: [deploy]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/slack-action@v1.0.0
        with:
          success-prefix: 🌲
          success: ${{ needs.deploy.result == 'success' }}
          webhook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
