name: development
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

jobs:
  init:
    runs-on: ubuntu-latest
    name: Apply environment protections rules
    environment: 
      name: development
      url: https://core-service-development.pine.loans
    steps:
      - run: echo 'Deploy development'
  
  build-and-test:
    needs: [init]
    name: Build and Test
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      run_tests: true

  terraform-check:
    needs: [init]
    name: Validate Terraform code
    uses: ./.github/workflows/reusable-terraform-check.yml
    secrets: inherit
    strategy:
      matrix:
        path: ["ops/terraform/development", "ops/terraform/staging", "ops/terraform/prod"]
    with:
      path: ${{ matrix.path }}
  
  deploy:
    needs: [build-and-test,terraform-check]
    name: Deploy `development`
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      cloud_run_service_name: core-service-development
      version: ${{ needs.build-and-test.outputs.version }}
      environment: development
      environment_url: https://core-service-development.pine.loans

  notify:
    name: Notify
    needs: deploy
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/slack-action@v1.0.0
        with:
          success-prefix: 🌲
          success: ${{ needs.deploy.result == 'success' }}
          webhook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
