name: Nightly (Staging)
on:
  schedule:
    - cron: '0 7 * * *' # 7AM UTC daily
jobs:
  build:
    name: Build
    uses: ./.github/workflows/jobs/build.yml
    with:
      push: false
      environment: staging
    secrets: inherit
  notify:
    name: Notify
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/slack-action@v1.0.0
        with:
          success-prefix: 🌲
          success: ${{ needs.build.result == 'success' }}
          webhook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
