name: Deploy
on:
  workflow_call:
    inputs:
      image_name:
        default: 'gcr.io/pinedefi/core-service'
        description: Specifies the Docker image name
        required: false
        type: string
      cloud_run_service_name:
        description: Name of the Google Cloud Run service to deploy
        required: true
        type: string
      version:
        description: Version that corresponds to image tag
        required: true
        type: string
      environment:
        description: Environment to deploy to
        required: true
        type: string
      preview:
        default: false
        description: Version that corresponds to image tag
        required: false
        type: boolean
      environment_url:
        default: ''
        description: Environment URL to be shown in GitHub Deployment interface
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout_ref }}
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Authenticate Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACC }}
      
      - name: Login to GCR
        uses: docker/login-action@v2.1.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      - name: Get `build` directory from Docker image to upload sourcemaps for Sentry releases integration
        run: docker cp $(docker create --name tc ${{ inputs.image_name }}:${{ inputs.version }}):/var/app/build ./build && docker rm tc
      
      - name: Create a GitHub Deployment
        uses: bobheadxi/deployments@v1.3.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          env: ${{ inputs.environment }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.cloud_run_service_name }}
          region: us-central1
          image: "${{ inputs.image_name }}:${{ inputs.version }}"
          tag: ${{ inputs.preview && inputs.version || 'latest' }}
          no_traffic: ${{ inputs.preview }}
      
      - name: Update traffic reference for non-preview envs
        if: ${{ !inputs.preview }}
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.cloud_run_service_name }}
          region: us-central1
          tag_traffic: latest=100
      
      - name: Deploy Cloud Scheduler jobs with Terraform
        # if: ${{ !inputs.preview }}
        if: ${{ inputs.preview }}
        working-directory: ops/jobs/development
        # working-directory: ops/jobs/${{ inputs.environment }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Create Sentry release
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.ORG_SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.ORG_SENTRY_ORG }}
          SENTRY_PROJECT: core-service
        with:
          environment: ${{ inputs.preview && 'development' || inputs.environment }}
          version: ${{ github.sha }}
          sourcemaps: 'build'
          ignore_missing: false
          strip_common_prefix: false
          url_prefix: '~/'
      
      - name: Update the GitHub Deployment status
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ inputs.preview && steps.deploy.outputs.url || inputs.environment_url }}
